### ISSUE TITLE
Invalid pool management

### ISSUE THREAD

**Issue by vitaly-t** [One-com/node-postgres-migrate#2]
As per comments here: https://github.com/One-com/node-postgres-migrate/commit/69644cf492f08229359e22f75d565b14cc4b343b

**Comment by gustavnikolaj** [comment]
Quote from the above mentioned commit - wan't to continue the discussion here and keep the context :-)

> This doesn't really do anything. There is no such option in pg-promise as poolSize.
> If you really want to achieve such effect, you need to do the following:
> 
> ```
> pgp.pg.defaults.poolSize = 0;
> ```
> 
> I'm not sure what it will do exactly, so I can't advise for or against this. This is not a common practice.

Thanks for reaching out @vitaly-t. I did that change in a hurry, while debugging connection pool exhaustion and obviously didn't test it thoroughly enough. Thanks for bringing it to my attention.

I was trying to read through some of your code, and I must have misread something, but I thought that you passed unknown options through to the vanilla pg module.

Setting the `poolSize` to 0 disables connection pooling in the pg module (which is enabled by default). I wanted to do that, as the migration stuff is something that you run as a one-off thing before bootstrapping an application - or before running it at all. Doing it this way, allows me to ignore connection pooling entirely, which was not really called for in the situation any way.

The specific problem that I thought I was solving was with a test suite that opened multiple connections to multiple different databases within the same postgres instance. Some of them through pg-promise, and some of them through knex which carries its own connection pool implementation. I wanted to simplify things, by only having one kind of pools in play, instead of having the default one from the postgres module on top.

**Comment by vitaly-t** [comment]
I believe you will get far better results by reducing the pool size. The default is 10. And if you set it to 2, it will be far better than disabling it.

That option belongs to `node-postgres` settings, it is not part of `pg-promise`. And the `node-posgres` instance is available from `pg-promise` via property `pg` as shown in the example.

See also: [FAQ: How to access the instance of node-postgres that's used?](https://github.com/vitaly-t/pg-promise/wiki/FAQ#how-to-access-the-instance-of-node-postgres-thats-used)

**Comment by gustavnikolaj** [comment]
I know that it's not common practice, but it's documented in the node-postgres module, and it is exactly what I think this situation call for. What do you think?

I know that the code I'm executing need to run in sequence, thus I have no need to fan out over multiple connections. One is enough, and no connection pooling behavior simplifies stuff a lot.

**Comment by vitaly-t** [comment]
Just keep in mind that the moment you try to execute something at the same time, you will run out of connections, which in turn may result in some queries to fail, if something else is taking too long to execute.

People who use full potential of the connection pool often have to implement an additional layer of a re-try when the connection pool is exhausted.

**Comment by gustavnikolaj** [comment]
@vitaly-t Given my rather limited use case here, I am very sure, that I'll never need to execute anything in parallel. In order to give the guarantees about the migrations that I need, I must execute sequentially anyway, so this is not a problem for my particular use case :-)

**Comment by gustavnikolaj** [comment]
Properly fixed in https://github.com/One-com/node-postgres-migrate/commit/61885a3c70b627db9b93a1038f5a4e339ea8dcb4 and released with v1.1.1
